export * from "./authController"
export * from "./healthController"
export * from "./moviesController"
export * from "./watchlistController"
export * from "./seriesController"
export * from "./artistController"
